---
title: "Pollinator Path Simulation"
author: "Alec Henriksen"
date: "July 8, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
library(markdown)
```

## R Markdown

3x3 Matrix
```{r}
One = c(.5,.1,.4)
Two = c(.1,.6,.3)
Three = c(.4,.3,.3)

Matrix = matrix(c(One, Two, Three), nrow=3, ncol=3, byrow = T)
Matrix

```
Counter and location
```{r}
#counter = c(0,0,0)
#beeLocation = 1
```

V 1.0 Loop
```{r}
ntrials = 1000
#trials = 50
#for(i in i:trials) {

  counter = c(0,0,0)
  beeLocation = 1

  for(i in 1:ntrials) {
    random.number = runif(1)
    if(beeLocation == 1) {
      if(random.number <= Matrix[1,1]) {
        beeLocation = 1
      } else if(random.number <= Matrix[1,1] + Matrix[1,2]) {
        beeLocation = 2
      } else {
        beeLocation = 3
      }
    }
    else if(beeLocation == 2) {
      if(random.number <= Matrix[2,1]) {
        beeLocation = 1
      } else if(random.number <= Matrix[2,1] + Matrix[2,2]) {
        beeLocation = 2
      } else {
        beeLocation = 3
      }
    }
    else if(beeLocation == 3) {
          if(random.number <= Matrix[3,1]) {
        beeLocation = 1
      } else if(random.number <= Matrix[3,1] + Matrix[3,2]) {
        beeLocation = 2
      } else {
        beeLocation = 3
      }
    }
    counter[beeLocation] = counter[beeLocation] + 1
  }
  print(counter)
#}  
```

Larger Matrix
```{r}
One = c(.4,.2,.2,.2,.0)
Two = c(.2,.4,.2,.2,.0)
Three = c(.2,.2,.4,.2,.0)
Four = c(.2,.2,.2,.3,.1)
Five = c(.0,.0,.0,.1,.9)

Matrix = matrix(c(One, Two, Three, Four, Five), nrow=5, ncol=5, byrow = T)
Matrix
```

V 2.0 Attempt to make loop read in the matrix.
```{r}
  ntrials = 1000
  counter = c(0,0,0,0,0)
  beeLocation = 1
  hold.number = 0

  for(i in 1:ntrials) {
    hold.number = 0
    random.number = runif(1)
    for(k in (1:ncol(Matrix))) {
     sum1 = hold.number + Matrix[beeLocation,k]
        
          
      if(random.number >= hold.number & random.number <= sum1) {
        beeLocation = k
        counter[beeLocation] = counter[beeLocation] + 1
      } 
      hold.number=sum1
           
      } 
     }

  counter

```

9x9 Matrix
```{r}
One = c(.11,.11,.11,.11,.11,.11,.11,.11,.12)
Two = c(.11,.11,.11,.11,.11,.11,.11,.11,.12)
Three = c(.11,.11,.11,.11,.11,.11,.11,.11,.12)
Four = c(.11,.11,.11,.11,.11,.11,.11,.11,.12)
Five = c(.11,.11,.11,.11,.11,.11,.11,.11,.12)
Six = c(.11,.11,.11,.11,.11,.11,.11,.11,.12)
Seven = c(.11,.11,.11,.11,.11,.11,.11,.11,.12)
Eight = c(.11,.11,.11,.11,.11,.11,.11,.11,.12)
Nine = c(.11,.11,.11,.11,.11,.11,.11,.11,.12)

Matrix = matrix(c(One, Two, Three, Four, Five, Six, Seven, Eight, Nine), nrow=9, ncol=9, byrow = T)
Matrix
```

V 3.0 Any matrix and the bee leaves after returning to the starting if all beds visited.
```{r}
  
  counter = c(0,0,0,0,0,0,0,0,0)
  beeLocation = 1
  hold.number = 0
  total.moves = 0
  done = F

 while(done == F | beeLocation != 1) {
    hold.number = 0
    sum1 = 0
    random.number = runif(1)
    for(k in (1:ncol(Matrix))) {
     sum1 = hold.number + Matrix[beeLocation,k]
        
          
     if(random.number >= hold.number & random.number <= sum1) {
        beeLocation = k
        print(beeLocation)
        counter[beeLocation] = counter[beeLocation] + 1
        total.moves = total.moves + 1
        if(total.moves > 4) {
          for(i in 1:length(counter)) {
            if(counter[i] == 0) {
              break
            }
            if(i == length(counter)) {
              done = T
           }
          }
        }
      } 
      hold.number=sum1
           
      } 
     }

  counter
  total.moves
```

V 4.0 9x9 matrix and the bee leaves after returning to the 
starting if all beds visited. Bee also starts at random location
```{r}
  #simulator <- function(Matrix) {
    Total.Moves.Vector = vector()
    Matrix = Matrix
    a = c(1,2,3,4,5,6,7,8,9)
      
    #for (j in 1:1000) {
      counter = c(0,0,0,0,0,0,0,0,0)
      startBeeLocation = sample(a,1)
      beeLocation = startBeeLocation
      hold.number = 0
      total.moves = 0
      done = F
      print(paste0("Starting Bee Location: ", startBeeLocation)) 
    
    
      while(done == F | beeLocation != startBeeLocation) {
        hold.number = 0
        sum1 = 0
        random.number = runif(1)
        for(k in (1:ncol(Matrix))) {
         sum1 = hold.number + Matrix[beeLocation,k]
            
              
         if(random.number >= hold.number & random.number <= sum1) {
            beeLocation = k
            print(beeLocation)
            counter[beeLocation] = counter[beeLocation] + 1
            total.moves = total.moves + 1
            if(total.moves > 8) {
              for(i in 1:length(counter)) {
                if(counter[i] == 0) {
                  break
                }
                if(i == length(counter)) {
                  done = T
               }
              }
            }
          } 
          hold.number=sum1
               
          } 
         }
      print(counter)
      print(total.moves)
      #Total.Moves.Vector[j] <- total.moves
      
    #}
    
  #print(mean(Total.Moves.Vector))
  #}
```


```{r}
simulator(Matrix)
```






















































